name: build-container

on:
  push:
    branches-ignore:
      - main
      - master
    tags:
      - 'v*'

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    environment: default
    env:
      K8S_PROJECT: pulse-engage-indexer
      K8S_CONTAINER: pulse-engage-indexer
      SLACK_DEPLOY_MSG:
    steps:
      - name: "Trigger Container Build"
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_WEBHOOK_TOKEN }}
          repository: istresearch/ci-docker
          event-type: build-repo
          client-payload: |-
            {
              "repo": {
                "name": "${{ github.repository }}",
                "ref_type": "${{ github.ref_type }}",
                "ref_name": "${{ github.ref_name }}"
              },
              "image": {
                "dockerfile": "Dockerfile",
                "name": "${{ github.repository }}",
                "get_version_bash": "cat VERSION",
                "build_args": [
                ]
              },
              "deployment": {
                "deploy_flag": "${{ github.ref_type == 'branch' }}",
                "k8s_project": "${{ env.K8S_PROJECT }}",
                "k8s_container": "${{ env.K8S_CONTAINER }}",
                "deploy_msg": "${{ env.SLACK_DEPLOY_MSG }}"
              },
              "callback": {
                "repository": "${{ github.repository }}",
                "event_type": "build_image_result",
                "error_type": "build_image_error"
              }
            }
  #endjob trigger-build
